import path from 'node:path';
import { ADAPTERS_DIR, DOCS_DIR, SUPPORTED_TOOLS } from './constants.mjs';
import { exists, writeText } from './fs-utils.mjs';
import { loadAllSkills, readJson } from './load-skills.mjs';

const toolLabel = (tool) => {
  if (tool === 'codex') return 'Codex';
  if (tool === 'claude') return 'Claude';
  if (tool === 'cursor') return 'Cursor';
  return 'Copilot';
};

const tierLabel = (tier) => {
  return tier === 'tier1' ? 'Full (Tier1)' : 'Limited (Tier2)';
};

const escapePipes = (value) => value.replace(/\|/g, '\\|');

const buildCell = (manifest) => {
  if (manifest === null) {
    return 'Not built';
  }

  const unsupported = manifest.unsupportedFeatures ?? [];
  if (unsupported.length === 0) {
    return tierLabel(manifest.tier);
  }

  return `${tierLabel(manifest.tier)}<br/><sub>${escapePipes(unsupported.join('; '))}</sub>`;
};

const loadManifestIfExists = async (tool, skillId) => {
  const manifestPath = path.join(ADAPTERS_DIR, tool, skillId, 'adapter-manifest.json');
  if (!(await exists(manifestPath))) {
    return null;
  }

  return readJson(manifestPath);
};

export const generateMatrix = async () => {
  const skills = await loadAllSkills();
  const rows = [];

  for (const skill of skills) {
    const manifests = {};
    for (const tool of SUPPORTED_TOOLS) {
      manifests[tool] = await loadManifestIfExists(tool, skill.skillId);
    }

    rows.push({
      skillId: skill.skillId,
      codex: buildCell(manifests.codex),
      claude: buildCell(manifests.claude),
      cursor: buildCell(manifests.cursor),
      copilot: buildCell(manifests.copilot)
    });
  }

  const header = [
    '# Compatibility Matrix',
    '',
    'This matrix is generated by `skillctl matrix` from adapter manifests.',
    '',
    '| Skill | Codex | Claude | Cursor | Copilot |',
    '| --- | --- | --- | --- | --- |'
  ];

  const lines = rows.map((row) => {
    return `| ${row.skillId} | ${row.codex} | ${row.claude} | ${row.cursor} | ${row.copilot} |`;
  });

  const toolSection = [
    '',
    '## Tool Targets',
    '',
    ...SUPPORTED_TOOLS.map((tool) => `- ${toolLabel(tool)} (${tool})`)
  ];

  const content = [...header, ...lines, ...toolSection, ''].join('\n');
  const outputPath = path.join(DOCS_DIR, 'compatibility-matrix.md');
  await writeText(outputPath, content);

  return {
    outputPath,
    skillCount: rows.length
  };
};
